# YeonSphere Universal Open Source License (YUOSL)
# Copyright (c) 2024 Jeremy Matlock (@daedaevibin)
# All rights reserved.
# See LICENSE for full terms.

# Example Seoggi project configuration

name: hello
version: 0.1.0
author: Jeremy Matlock (@daedaevibin)
description: A simple hello world program in Seoggi

# Build configuration
entry_point: main.seo
sources:
  - main.seo
  - greeter.seo

# Dependencies (none for this example)
dependencies: []

# Test configuration
test_dir: tests

# Output configuration
output_dir: build
